### ISSUE TITLE
rune: rune exec Warm images does not output on the correct terminal

### ISSUE THREAD

**Issue by haosanzi** [alibaba/inclavare-containers#1124] opened 2021-06-18 09:42 UTC
```c
cat test.c
#include <stdio.h>
#include <unistd.h>

int main() {
    while(1){
      printf("Test Test Test!\n");
      sleep(10);
    }
}

cat hello.c
#include <stdio.h>
#include <unistd.h>

int main() {
    while(1){
      printf("Hello World!\n");
      sleep(10);
    }
}

/opt/wasi-sdk/bin/clang -O3 -o test.wasm test.c
/opt/wasi-sdk/bin/clang -O3 -o hello.wasm hello.c
wamrc -sgx -o test.aot test.wasm
wamrc -sgx -o hello.aot hello.wasm
```
Use the following Dockerfile to build warm images contains the above c application.
```Dockerfile
FROM centos:8.2.2004
RUN mkdir -p /run/rune
WORKDIR /run/rune
COPY enclave.signed.so .
COPY test.aot test
COPY hello.aot hello
ENTRYPOINT ["/run/rune/test"]
```

The test `rune exec` command:
```
# On terminal 1
rune --debug run 666
# On terminal 2
rune --debug exec 666 /run/rune/hello
```

The result is shown in the following.  The content of rune exec is incorrect output to the terminal of `rune run` process.

![image](https://user-images.githubusercontent.com/26923638/122541311-13a3c280-d05c-11eb-982b-b3d7c972a003.png)

**Comment by lifeng68** [comment] 2021-06-19 01:51
@haosanzi I read the code and guess it's because `wamr_stdio_fds_t` is not handled correctly in libwamr-pal.so, is it right? Can you give me some guidance, I can try to modify this issue.

**Comment by jiazhang0** [comment] 2021-06-19 02:06
@lifeng68 You are right. This is due to the fact that libwamr-pal.so doesn't correctly handle the fds. The fds 0,1,2 are the right stdio for the first wamr application launched by docker run, so even libwamr-pal.so doesn't populate fds the results are still expected. However, the fds 3,4,5 as stdio are passed to the second wamr application and the results are unexpected if not populated. See https://github.com/alibaba/inclavare-containers/blob/master/rune/libenclave/internal/runtime/pal/spec_v2.md#3pal_create_process and https://github.com/alibaba/inclavare-containers/blob/master/rune/libenclave/internal/runtime/pal/spec_v2.md#3pal_create_process. libwamr-pal.so doesn't handle args->stdio at all.

**Comment by lifeng68** [comment] 2021-06-19 02:23
> populated

@jiazhang0 Yes, So we should populate the fds to WAMR running in enclave? 
I read the app.cpp and did not find the functions can  to pupulate the fds to second wamr application? Did wamr support to replace stdin\stdout\stderr?  I'm a new WAMR, I don't know much about it. Thanks.
```
typedef enum EcallCmd {
    CMD_INIT_RUNTIME = 0,     /* wasm_runtime_init/full_init() */
    CMD_LOAD_MODULE,          /* wasm_runtime_load() */
    CMD_INSTANTIATE_MODULE,   /* wasm_runtime_instantiate() */
    CMD_LOOKUP_FUNCTION,      /* wasm_runtime_lookup_function() */
    CMD_CREATE_EXEC_ENV,      /* wasm_runtime_create_exec_env() */
    CMD_CALL_WASM,            /* wasm_runtime_call_wasm */
    CMD_EXEC_APP_FUNC,        /* wasm_application_execute_func() */
    CMD_EXEC_APP_MAIN,        /* wasm_application_execute_main() */
    CMD_GET_EXCEPTION,        /* wasm_runtime_get_exception() */
    CMD_DEINSTANTIATE_MODULE, /* wasm_runtime_deinstantiate() */
    CMD_UNLOAD_MODULE,        /* wasm_runtime_unload() */
    CMD_DESTROY_RUNTIME,      /* wasm_runtime_destroy() */
    CMD_SET_WASI_ARGS,        /* wasm_runtime_set_wasi_args() */
    CMD_SET_LOG_LEVEL,        /* bh_log_set_verbose_level() */
} EcallCmd;
```

**Comment by jiazhang0** [comment] 2021-06-19 03:00
@lifeng68 Good question. 

In all enclave contexts, it is impossible to call printf or any operations which directly pupulates fd. So the solution is to define an OCALL (e.g, https://github.com/jiazhang0/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.edl#L22) called in enclave context, and the real OCALL handler is defined in untrusted side (e.g, https://github.com/jiazhang0/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/App/App.cpp#L43). As you see, it is simply a printf which uses fd 2 as stdout. This is the root cause.

I'm not wamr expert as well so I just explored the pal codes to give my guess. wamr_pal_create_process() should pass new stdio fds to init_runtime() and then to CMD_INIT_RUNTIME subcmd handler at https://github.com/jiazhang0/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.cpp#L70. `os_set_print_function(enclave_print)` is used to set the print function which eventually uses OCALL as mentioned above. Unfortunately it seems to not pass fd as a parameter to enclave_print(), so maybe we have to do it in this way:

```
// global variables
static int stdio[3];
// need to initialize to -1 in some place before being accessed.
static int stdin_table[MAX_STDIO_FDS];
...
handle_cmd_init_runtime() {
  ...
  int stdout = (int)args[4];

  // stdout_table is used to debug purpose against new app creation with the existing fd
  if (stdout_table[stdout] != -1) {
    // error handling
  }

  stdout_table[stdout] = stdout;
  stdio[1] = stdout;

  os_set_print_function(enclave_print);
  ...
```

and enclave_print() needs to pass stdio[1] to ocall_print(), so this OCALL handler needs to be extended as well.

All above is complex and the stdio fd is eventually passed to ocall_print() in untrusted side. So it is wise to bind the stdio fds retrieved from wamr_pal_create_process() to the fd parameter consumed by ocall_print().

**Comment by jiazhang0** [comment] 2021-06-19 03:05
@lifeng68 ocall_print() with fd extension needs to populate fd. Using dup2() is necessary. Refer to https://www.cs.utexas.edu/~theksong/2020/243/Using-dup2-to-redirect-output/ and https://stackoverflow.com/questions/26434429/how-to-redirect-printf-to-file-and-then-back-to-console.

**Comment by lifeng68** [comment] 2021-06-19 03:13
Thanks very much, I'll study your suggestion and try to implement it.

**Comment by lifeng68** [comment] 2021-06-19 06:54
> @lifeng68 Good question.
> 
> In all enclave contexts, it is impossible to call printf or any operations which directly pupulates fd. So the solution is to define an OCALL (e.g, https://github.com/jiazhang0/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.edl#L22) called in enclave context, and the real OCALL handler is defined in untrusted side (e.g, https://github.com/jiazhang0/wasm-micro-runtime/blob/main/product-mini/platforms/linux-sgx/enclave-sample/App/App.cpp#L43). As you see, it is simply a printf which uses fd 2 as stdout. This is the root cause.

@jiazhang0 I tested the code, found that our guess may be wrong. I modify the ocall_print in App.cpp and add prefix 1111 for test as blow:

```
void
ocall_print(const char* str)
{
    printf("1111:%s", str);
}
```
Then i fixed my test wasm application as beblow, then rebuild the wasm image.

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    char *buf;

    printf("Hello world!\n");

    buf = malloc(1024);
    if (!buf) {
        printf("malloc buf failed\n");
        return -1;
    }

    printf("buf ptr: %p\n", buf);

    sprintf(buf, "%s", "1234\n");
    printf("buf: %s", buf);

    fprintf(stdout, "stdout: 2222\n");
    fprintf(stderr, "stderr: 2222\n");

    free(buf);
    return 0;
}
```

When run the image, i got the output:
```
sudo docker run -it --runtime=rune  \
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  wamr-sgx-app
1111:os_printf
Hello world!
buf ptr: 0x11530
buf: 1234
stdout: 2222
stderr: 2222
```

So, we can find that the `printf \fprintf ` funtion in the WASM application did not call the ocall_print in untrusted side. Then we cannot fix this issue by extend ocall_print.  I found same issue in WAMR project, https://github.com/bytecodealliance/wasm-micro-runtime/issues/482, may be we should do `fd_table_insert_existing(curfds, 1, OURSTDOUT)`  to replace the stdout\stderr fd with our fds.

**Comment by jiazhang0** [comment] 2021-06-19 07:18
@lifeng68 See https://github.com/jiazhang0/wasm-micro-runtime/blob/main/doc/linux_sgx.md:

```
Step 5: To support log output and os_printf() function in Enclave, please implement an ocall_print function, e.g. in Enclave.edl, add:

untrusted {
    void ocall_print([in, string]const char* str);
};

In App part, add:

void
ocall_print(const char* str)
{
    printf("%s", str);
}

And in Enclave part, set the print function:

#include "wasm_export.h"
#include "bh_platform.h"

extern "C" {
    typedef void (*os_print_function_t)(const char* message);
    extern void os_set_print_function(os_print_function_t pf);

    void
    enclave_print(const char *message)
    {
        ocall_print(message);
    }
}

// In the beginning of Enclave initialization, add:
os_set_print_function(enclave_print);
```

The "App" part mentioned above is actually the warm PAL rather than wamr app. The wamr app may print message through wasi stdio and might buffers all output in a single call to os_printf(). I mean it is possible that all your warm app outputs are assembled into a single buffer and finally printed by os_printf() -> enclave_print() -> ocall_print(), e.g, `Hello world!\nbuf ptr: 0x11530\n...`. So you can try to add fflush() following each print/fprintf in your wamr app to see what happens.

**Comment by lifeng68** [comment] 2021-06-19 07:35
> @lifeng68 See https://github.com/jiazhang0/wasm-micro-runtime/blob/main/doc/linux_sgx.md:
> 
> ```
> Step 5: To support log output and os_printf() function in Enclave, please implement an ocall_print function, e.g. in Enclave.edl, add:
> 
> untrusted {
>     void ocall_print([in, string]const char* str);
> };
> 
> In App part, add:
> 
> void
> ocall_print(const char* str)
> {
>     printf("%s", str);
> }
> 
> And in Enclave part, set the print function:
> 
> #include "wasm_export.h"
> #include "bh_platform.h"
> 
> extern "C" {
>     typedef void (*os_print_function_t)(const char* message);
>     extern void os_set_print_function(os_print_function_t pf);
> 
>     void
>     enclave_print(const char *message)
>     {
>         ocall_print(message);
>     }
> }
> 
> // In the beginning of Enclave initialization, add:
> os_set_print_function(enclave_print);
> ```
> 
> The "App" part mentioned above is actually the warm PAL rather than wamr app. The wamr app may print message through wasi stdio and might buffers all output in a single call to os_printf(). I mean it is possible that all your warm app outputs are assembled into a single buffer and finally printed by os_printf() -> enclave_print() -> ocall_print(), e.g, `Hello world!\nbuf ptr: 0x11530\n...`. So you can try to add fflush() following each print/fprintf in your wamr app to see what happens.

No, when i add the fflush(stdout)\fflush(stderr) the output is same. 

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(int argc, char **argv)
{
    char *buf;

    printf("Hello world!\n");

    buf = malloc(1024);
    if (!buf) {
        printf("malloc buf failed\n");
        return -1;
    }

    printf("buf ptr: %p\n", buf);
    fflush(stdout);

    sprintf(buf, "%s", "1234\n");
    printf("buf: %s", buf);
    fflush(stdout);

    fprintf(stdout, "stdout: 2222\n");
    fflush(stdout);
    fprintf(stderr, "stderr: 2222\n");
    fflush(stderr);

    free(buf);
    return 0;
}
```

```
platforms/linux-sgx/enclave-sample ‹main*› » sudo docker run -it --runtime=rune  \
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  wamr-sgx-app
1111:os_printf
Hello world!
buf ptr: 0x11530
buf: 1234
stdout: 2222
stderr: 2222
```

And i tested that do not call the ocall_print in enclave_print in Enclave.app , like:

```
    void
    enclave_print(const char *message)
    {
        return;
        ocall_print(message);
    }
```
Then rebuild the image, found that we can get the output as before. So the output of WAMR application did not call the ocall_print.
```
platforms/linux-sgx/enclave-sample ‹main*› » sudo docker run -it --runtime=rune  \
  -e ENCLAVE_TYPE=intelSgx \
  -e ENCLAVE_RUNTIME_PATH=/usr/lib/libwamr-pal.so \
  -e ENCLAVE_RUNTIME_ARGS=debug \
  wamr-sgx-app
Hello world!
buf ptr: 0x11530
buf: 1234
stdout: 2222
stderr: 2222
```

**Comment by lifeng68** [comment] 2021-06-19 08:56
@jiazhang0 I did some modification to WAMR, and tested work fine. Please help to reivew, thanks.

**Comment by lifeng68** [comment] 2021-06-22 06:51
@haosanzi @jiazhang0 https://github.com/bytecodealliance/wasm-micro-runtime/pull/655 had been merged, i think we can close this issue.

**Comment by jiazhang0** [comment] 2021-06-22 06:52
@lifeng68 Good job! This issue will be kept till @haosanzi updates the wamr testing image.

**Comment by haosanzi** [comment] 2021-06-23 04:13
`inclavarecontainers/enclave-wamr:latest` image has been updated.

**Closed** 2021-06-23 04:15 UTC
Labels: bug, gating, high
