### ISSUE TITLE
verdictd: build failure

### ISSUE THREAD

**Issue by jiazhang0** [alibaba/inclavare-containers#1328] opened 2021-08-27 13:24 UTC
Refer to: https://github.com/alibaba/inclavare-containers/pull/1326/checks?check_run_id=3443167887

```
    Compiling shadow-rs v0.5.25
   Compiling verdictd v0.0.1 (/__w/inclavare-containers/inclavare-containers/verdictd/app)
warning: unused variable: `request`
  --> src/configure_provider/provider.rs:82:9
   |
82 |         request: Request<DeleteKeyRequest>,
   |         ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_request`
   |
   = note: `#[warn(unused_variables)]` on by default

error: linking with `cc` failed: exit status: 1
```

**Comment by liangzhou121** [comment] 2021-08-28 12:25
The root cause is verdictd can't find "enclave_tls_set_verification_callback" function's definitation during linking stage. And this fundtion is defined inside rats-tls generated enclave-tls.so lib.
So it should be Yangliang's "only install enclave-tls sdk files to /opt/enclave-tls" PR's problem. I will assign this issue to him to do some further investigation.

The error info:
  = note: /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /__w/inclavare-containers/inclavare-containers/verdictd/app/target/release/deps/verdictd-73cabb1ce9dfadb3.verdictd.85id9gnf-cgu.11.rcgu.o: in function `verdictd::enclave_tls::EnclaveTls::new':
          verdictd.85id9gnf-cgu.11:(.text._ZN8verdictd11enclave_tls10EnclaveTls3new17h615e7243309804c8E+0x1c2): undefined reference to `enclave_tls_set_verification_callback'
          collect2: error: ld returned 1 exit status

**Comment by YangLiang3** [comment] 2021-08-30 04:34
@liangzhou121 enclave_tls_set_verification_callback is defined, you can use it in verdict， right？

**Comment by YangLiang3** [comment] 2021-08-30 05:56
In verdicd Makefile, /opt/enclave-tls/lib need be changed as enclave tls default path is modified. 
 @cd app && RUSTFLAGS="-C link-args=-Wl,-rpath=/opt/enclave-tls/lib:/usr/local/lib:$(PROJDIR)/verdictd/lib,--enable-new-dtags" cargo build $(App_Rust_Flags)

**Closed** 2021-08-30 10:40 UTC
Labels: bug, high, gating
